### ISSUE TITLE
 lowercase problem with writeConfig

### ISSUE THREAD

**Issue by simonechiarucci** [amattana/skalab#3]
The method writeConfig in skalab_base.py uses configparser. When using writeConfig, it converts all read strings to lower case.
Attribute optionxform should solve this problem.

Possible solution:
def writeConfig(self, profileConfig, fname):
        conf = configparser.ConfigParser()
        conf.optionxform = str

**Comment by amattana** [comment]
Thanks. 
Implemented in the branch_test, it will be merged soon in the master.
